let data = [
  {
    id: 1,
    title: "BMW Serie 3 (G20)",
    details:
      "Sedán deportivo de lujo con excelente rendimiento y tecnología avanzada.",
    img: "https://66d9ee6caa07a954166f10ed--gregarious-melba-cacdba.netlify.app/1.jpg",
    price: 43300,
    stock: 28,
    category: "De lujo",
  },
  {
    id: 2,
    title: "Alfa Romeo 4C Spider",
    details:
      "Ligero, ágil y de diseño exótico, ideal para quienes buscan deportividad pura.",
    img: "https://66d9ee6caa07a954166f10ed--gregarious-melba-cacdba.netlify.app/2.jpg",
    price: 64824,
    stock: 42,
    category: "Deportivos",
  },
  {
    id: 3,
    title: "Mercedes-Benz AMG GT",
    details:
      "Coupé de alto rendimiento, diseño elegante y potencia impresionante.",
    img: "https://66d9ee6caa07a954166f10ed--gregarious-melba-cacdba.netlify.app/3.jpg",
    price: 89063,
    stock: 42,
    category: "De lujo",
  },
  {
    id: 4,
    title: "Audi RS7",
    details: "Sedán de alta gama, combina lujo con rendimiento sobresaliente.",
    img: "https://66d9ee6caa07a954166f10ed--gregarious-melba-cacdba.netlify.app/4.jpg",
    price: 82322,
    stock: 33,
    category: "De lujo",
  },
  {
    id: 5,
    title: "Ferrari 250 GT Spyder",
    details: "Ícono clásico con un diseño atemporal y exclusividad única.",
    img: "https://66d9ee6caa07a954166f10ed--gregarious-melba-cacdba.netlify.app/5.jpg",
    price: 83055,
    stock: 48,
    category: "Clásicos",
  },
  {
    id: 6,
    title: "Lamborghini Aventador",
    details: "Superdeportivo potente y agresivo, con un diseño inconfundible.",
    img: "https://66d9ee6caa07a954166f10ed--gregarious-melba-cacdba.netlify.app/6.jpg",
    price: 524745,
    stock: 81,
    category: "Deportivos",
  },
  {
    id: 7,
    title: "Chevrolet Bel Air",
    details: "Clásico americano, símbolo de la época dorada del automovilismo.",
    img: "https://66d9ee6caa07a954166f10ed--gregarious-melba-cacdba.netlify.app/7.jpg",
    price: 83866,
    stock: 29,
    category: "Clásicos",
  },
  {
    id: 8,
    title: "Dodge Challenger SRT",
    details: "Muscle car con un motor poderoso y aspecto retro-moderno.",
    img: "https://66d9ee6caa07a954166f10ed--gregarious-melba-cacdba.netlify.app/8.jpg",
    price: 61010,
    stock: 23,
    category: "Deportivos",
  },
  {
    id: 9,
    title: "Maserati Gran Turismo",
    details:
      "Gran turismo de lujo, combina elegancia con rendimiento deportivo.",
    img: "https://66d9ee6caa07a954166f10ed--gregarious-melba-cacdba.netlify.app/9.jpg",
    price: 76113,
    stock: 84,
    category: "Deportivos",
  },
];
